spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.discovery.client.simple.enabled=true


jwt.expiration=8000000000
jwt.secret=${SECRET_KEY}

# Zipkin Configuration
management.tracing.sampling.probability=1.0
management.tracing.enabled=true